"""add ondelete set null to users.team_id

Revision ID: 2181690ebf44
Revises: b39b0b6f984a
Create Date: 2026-01-14 20:36:23.973574

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2181690ebf44'
down_revision = 'b39b0b6f984a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_team_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_team_id_fkey'), 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
