"""fix_permitindo_usuarios_pertencerem_a_varios_times

Revision ID: b39b0b6f984a
Revises: 3fabf50121d9
Create Date: 2026-01-13 23:58:41.246687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b39b0b6f984a'
down_revision = '3fabf50121d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_team_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_team_id_key'), 'users', ['team_id'])
    # ### end Alembic commands ###
