"""fix_ambiguidade_relacionamentos

Revision ID: cdaba7bacd33
Revises: 137fc9e7a44b
Create Date: 2026-01-11 19:16:08.692223

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cdaba7bacd33'
down_revision = '137fc9e7a44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.create_foreign_key(None, 'teams', 'users', ['leader_id'], ['id'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    # ### end Alembic commands ###
